Ft oop code conversion
Code-250/Blog_Plaza pull request #7
Opened 2021-03-17 10:18 UTC by Code-250

Hello I have managed to convert my api into OOP codes 
by that 

- I am able to perform CRUD operations to posts
- I have managed to protect routes
- managed to log and register users
- able to delete user.

2021-03-17 10:29 UTC, RedJanvier requested changes
You are not catching errors in some of your controllers please fix it ASAP!

2021-03-17 10:29 UTC, RedJanvier commented on Src/App/Helpers/validation.js
> +const createPost = Joi.object().keys({
Can you also convert this file to a class?

2021-03-17 10:29 UTC, RedJanvier commented on Src/App/Middlewares/authMidleware.js
> +export const routeProtect = (req, res, next) => {
This must also be a class not a standalone function.

2021-03-17 10:29 UTC, RedJanvier commented on Src/App/utils/errorHandler.js
> +export default (res, status, messsage) => {
Can you combine this and successHandler into a single function please?

2021-03-17 10:29 UTC, RedJanvier commented on Src/App/Controllers/authController.js
> +  static async getUsers(req, res, next) {
Why are you not catching errors in this controller?

2021-03-17 10:29 UTC, RedJanvier commented on Src/App/Controllers/authController.js
> +  static async deleteUser(req, res, next) {
You need to catch errors that might occur!

2021-03-17 10:29 UTC, RedJanvier commented on .env
>  PORT = 8080
Please remove this file! This is a necessity now on. Your PR will not be merged if this file is in it!

2021-03-17 14:01 UTC, RedJanvier approved these changes

2021-03-18 09:49 UTC, Procech20 approved these changes
Looks good to me!

2021-03-18 09:50 UTC, merged